import { Transaction, Asset } from '../types';
import { MetricCard } from './aura/AuraCards';

export function PfReports({ transactions = [], assets = [], isPrivacyMode = false }: { transactions?: Transaction[]; assets?: Asset[]; isPrivacyMode?: boolean }) {
  const rows = transactions.filter(row => row.context === 'PF');
  const income = rows.filter(row => row.type === 'income').reduce((sum, row) => sum + row.amount, 0);
  const expenses = rows.filter(row => row.type === 'expense').reduce((sum, row) => sum + row.amount, 0);
  const categories = Object.entries(rows.filter(row => row.type === 'expense').reduce<Record<string, number>>((map, row) => { map[row.category] = (map[row.category] || 0) + row.amount; return map; }, {}));
  return <div className="space-y-8"><div><h1 className="text-3xl font-extrabold text-slate-900">Relatórios PF</h1><p className="text-slate-500 mt-1">Indicadores derivados das transações reais.</p></div>{rows.length === 0 && assets.length === 0 ? <div className="p-16 text-center bg-white rounded-2xl border border-dashed border-slate-300 text-slate-500">Nenhum dado disponível</div> : <><div className="grid grid-cols-1 md:grid-cols-3 gap-6"><MetricCard title="Receitas" value={income} isPrivacyMode={isPrivacyMode} subtitle="Registros reais" /><MetricCard title="Despesas" value={expenses} isPrivacyMode={isPrivacyMode} subtitle="Registros reais" /><MetricCard title="Patrimônio" value={assets.reduce((sum, row) => sum + row.value, 0)} isPrivacyMode={isPrivacyMode} subtitle="Ativos cadastrados" /></div><div className="p-6 bg-white rounded-2xl border border-slate-200"><h2 className="font-bold text-slate-900">Despesas por categoria</h2>{categories.length === 0 ? <p className="mt-4 text-sm text-slate-500">Nenhum dado disponível</p> : <div className="mt-4 space-y-2">{categories.map(([category, amount]) => <div key={category} className="flex justify-between text-sm"><span>{category}</span><strong>R$ {amount.toLocaleString('pt-BR')}</strong></div>)}</div>}</div></>}</div>;
}
