import { Transaction, TransactionAnalytics } from '../types';
import { RefreshCcw, Download } from 'lucide-react';

export function PjAccounting({ transactions = [], analytics, onExportJson, onReimburse }: { transactions?: Transaction[]; analytics?: TransactionAnalytics; onExportJson?: () => Promise<unknown>; onReimburse: () => void }) {
  const rows = transactions.filter(row => row.context === 'PJ');
  const pending = rows.filter(row => row.isPaidByPF && !row.reimbursed);
  const reimbursement = Number(analytics?.paid_by_pf_cents || 0) / 100 || pending.reduce((sum, row) => sum + row.amount, 0);
  const personal = rows.filter(row => row.isPersonalExpenseInPJ);
  const exportPackage = async () => { const data = await onExportJson?.(); if (data == null) return; const blob = new Blob([JSON.stringify(data, null, 2)], { type: 'application/json' }); const url = URL.createObjectURL(blob); const anchor = document.createElement('a'); anchor.href = url; anchor.download = 'aurafin-pacote-contabil.json'; anchor.click(); URL.revokeObjectURL(url); };
  return <div className="space-y-8 text-slate-100"><div className="flex items-center justify-between border-b border-white/10 pb-4"><div><h1 className="text-2xl font-black text-white">Central Contábil</h1><p className="text-xs text-slate-400 mt-1">Conciliação e exportação server-side.</p></div><button onClick={() => void exportPackage()} className="flex items-center gap-2 px-4 py-2 bg-cyan-600 rounded-xl text-xs font-bold"><Download className="w-4 h-4" />Exportar JSON</button></div>{reimbursement > 0 && <div className="p-5 bg-slate-900 border border-amber-500/30 rounded-2xl flex items-center justify-between"><span className="text-sm">Reembolso pendente: <strong>{reimbursement.toLocaleString('pt-BR', { style: 'currency', currency: 'BRL' })}</strong></span><button onClick={onReimburse} className="flex items-center gap-2 px-3 py-2 bg-amber-500 text-slate-950 rounded-lg text-xs font-bold"><RefreshCcw className="w-4 h-4" />Reembolsar</button></div>}{rows.length === 0 ? <div className="p-16 text-center bg-slate-900 rounded-2xl border border-dashed border-white/10 text-slate-400">Nenhum dado disponível</div> : <div className="p-6 bg-slate-900 rounded-2xl border border-white/5"><h2 className="font-bold">Uso pessoal na PJ</h2>{personal.length === 0 ? <p className="mt-3 text-sm text-slate-400">Nenhum dado disponível</p> : <div className="mt-3 space-y-2">{personal.map(row => <div key={row.id} className="flex justify-between text-sm"><span>{row.title}</span><strong>{row.amount.toLocaleString('pt-BR', { style: 'currency', currency: 'BRL' })}</strong></div>)}</div>}</div>}</div>;
}
