import { Transaction } from '../types';
import { MetricCard } from './aura/AuraCards';
import { Download, FileText } from 'lucide-react';

interface Props { transactions?: Transaction[]; isPrivacyMode?: boolean; onExportCsv?: () => Promise<string>; onExportJson?: () => Promise<unknown>; }
export function PjAccountantHubView({ transactions = [], isPrivacyMode = false, onExportCsv, onExportJson }: Props) {
  const receipts = transactions.filter(row => row.context === 'PJ' && row.type === 'income').reduce((sum, row) => sum + row.amount, 0);
  const expenses = transactions.filter(row => row.context === 'PJ' && row.type === 'expense').reduce((sum, row) => sum + row.amount, 0);
  if (transactions.length === 0) return <div className="space-y-8 animate-in fade-in duration-200 text-slate-100"><div className="flex items-center justify-between border-b border-white/10 pb-4"><div><h1 className="text-2xl font-black text-white">Central do Contador</h1><p className="text-xs text-slate-400 mt-1">Fechamento derivado dos dados reais.</p></div></div><div className="p-16 text-center bg-[#0F172A] rounded-2xl border border-dashed border-white/10 text-slate-400"><FileText className="w-10 h-10 mx-auto mb-3 text-slate-600" />Nenhum dado disponível</div></div>;
  const exportFile = async (format: 'csv' | 'json') => { const data = format === 'csv' ? await onExportCsv?.() : await onExportJson?.(); if (data == null) return; const blob = new Blob([format === 'json' ? JSON.stringify(data, null, 2) : String(data)], { type: format === 'json' ? 'application/json' : 'text/csv' }); const url = URL.createObjectURL(blob); const anchor = document.createElement('a'); anchor.href = url; anchor.download = `aurafin-contador.${format}`; anchor.click(); URL.revokeObjectURL(url); };
  return <div className="space-y-8 animate-in fade-in duration-200 text-slate-100"><div className="flex items-center justify-between border-b border-white/10 pb-4"><div><h1 className="text-2xl font-black text-white">Central do Contador</h1><p className="text-xs text-slate-400 mt-1">Fechamento e exportação derivados dos dados reais.</p></div><div className="flex gap-2"><button onClick={() => void exportFile('csv')} className="flex items-center gap-2 px-3 py-2 bg-slate-900 rounded-xl text-xs font-bold"><Download className="w-4 h-4" />CSV</button><button onClick={() => void exportFile('json')} className="flex items-center gap-2 px-3 py-2 bg-cyan-600 rounded-xl text-xs font-bold"><Download className="w-4 h-4" />JSON</button></div></div><div className="grid grid-cols-2 md:grid-cols-3 gap-4"><MetricCard title="Receitas na página" value={receipts} isPrivacyMode={isPrivacyMode} subtitle="A página atual" /><MetricCard title="Despesas na página" value={expenses} isPrivacyMode={isPrivacyMode} subtitle="A página atual" /><MetricCard title="Registros carregados" value={transactions.length} prefix="" subtitle="Paginação server-side" /></div>{transactions.length === 0 ? <div className="p-16 text-center bg-[#0F172A] rounded-2xl border border-dashed border-white/10 text-slate-400"><FileText className="w-10 h-10 mx-auto mb-3 text-slate-600" />Nenhum dado disponível</div> : <div className="p-6 bg-[#0F172A] rounded-2xl border border-white/5 text-sm text-slate-300">O pacote do contador é gerado pelo endpoint server-side e não depende de um array histórico completo.</div>}</div>;
}
