import { useState } from 'react';
import { CreditCard, Account, Transaction } from '../types';
import { MetricCard } from './aura/AuraCards';
import { Plus, CreditCard as CreditCardIcon } from 'lucide-react';

interface Props { creditCards?: CreditCard[]; accounts?: Account[]; transactions?: Transaction[]; isPrivacyMode?: boolean; onAddCard?: () => void; onPayInvoice?: (cardId: string, amount: number) => void; }
const money = (v: number) => v.toLocaleString('pt-BR', { style: 'currency', currency: 'BRL' });

export function PjCardsView({ creditCards = [], isPrivacyMode = false, onAddCard, onPayInvoice }: Props) {
  const [filter, setFilter] = useState<'todos' | 'credito' | 'debito'>('todos');
  const cards = creditCards.filter(card => card.context === 'PJ');
  const creditCardsOnly = cards.filter(card => card.type === 'credito');
  const visibleCards = cards.filter(card => filter === 'todos' || card.type === filter);
  const totalLimit = creditCardsOnly.reduce((sum, card) => sum + card.limitTotal, 0);
  const totalUsed = creditCardsOnly.reduce((sum, card) => sum + card.limitUsed, 0);
  const totalInvoices = creditCardsOnly.reduce((sum, card) => sum + card.currentInvoice, 0);
  if (cards.length === 0) return <div className="space-y-8 animate-in fade-in duration-200 text-slate-100"><div className="flex items-center justify-between border-b border-white/10 pb-4"><div><h1 className="text-2xl font-black tracking-tight text-white">Cartões Empresariais</h1><p className="text-xs text-slate-400 mt-1">Cartões da organização ativa.</p></div><button onClick={onAddCard} className="flex items-center gap-2 px-4 py-2.5 bg-cyan-600 text-white font-bold rounded-xl text-xs"><Plus className="w-4 h-4" />Novo cartão</button></div><div className="p-16 text-center bg-[#0F172A] rounded-2xl border border-dashed border-white/10"><CreditCardIcon className="w-10 h-10 text-slate-600 mx-auto mb-3" /><p className="text-slate-400">Nenhum dado disponível</p><button onClick={onAddCard} className="mt-4 px-4 py-2 bg-cyan-600 text-white rounded-xl text-xs font-bold">Adicionar cartão</button></div></div>;
  return <div className="space-y-8 animate-in fade-in duration-200 text-slate-100">
    <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 border-b border-white/10 pb-4"><div><h1 className="text-2xl font-black tracking-tight text-white">Cartões Empresariais</h1><p className="text-xs text-slate-400 mt-1">Cartões reais cadastrados para a organização ativa.</p></div><button onClick={onAddCard} className="flex items-center gap-2 px-4 py-2.5 bg-cyan-600 text-white font-bold rounded-xl text-xs"><Plus className="w-4 h-4" />Novo Cartão</button></div>
    <div className="grid grid-cols-2 md:grid-cols-5 gap-4"><MetricCard title="Cartões Ativos" value={cards.length} prefix="" subtitle="Registros reais" /><MetricCard title="Limite Total" value={totalLimit} isPrivacyMode={isPrivacyMode} subtitle="Crédito cadastrado" /><MetricCard title="Limite Utilizado" value={totalUsed} isPrivacyMode={isPrivacyMode} subtitle="Valor informado" /><MetricCard title="Limite Disponível" value={Math.max(0, totalLimit - totalUsed)} isPrivacyMode={isPrivacyMode} subtitle="Calculado em centavos" /><MetricCard title="Faturas em Aberto" value={totalInvoices} isPrivacyMode={isPrivacyMode} subtitle="Valor informado" /></div>
    <div className="flex items-center gap-2 p-3 rounded-xl bg-[#0F172A] border border-white/5"><button onClick={() => setFilter('todos')} className={`px-3 py-2 text-xs font-bold rounded-lg ${filter === 'todos' ? 'bg-cyan-600 text-white' : 'text-slate-400'}`}>Todos ({cards.length})</button><button onClick={() => setFilter('credito')} className={`px-3 py-2 text-xs font-bold rounded-lg ${filter === 'credito' ? 'bg-cyan-600 text-white' : 'text-slate-400'}`}>Crédito ({creditCardsOnly.length})</button><button onClick={() => setFilter('debito')} className={`px-3 py-2 text-xs font-bold rounded-lg ${filter === 'debito' ? 'bg-cyan-600 text-white' : 'text-slate-400'}`}>Débito ({cards.filter(card => card.type === 'debito').length})</button></div>
    {visibleCards.length === 0 ? <div className="p-16 text-center bg-[#0F172A] rounded-2xl border border-dashed border-white/10"><CreditCardIcon className="w-10 h-10 text-slate-600 mx-auto mb-3" /><p className="text-slate-400">Nenhum dado disponível</p><button onClick={onAddCard} className="mt-4 px-4 py-2 bg-cyan-600 text-white rounded-xl text-xs font-bold">Adicionar cartão</button></div> : <div className="grid grid-cols-1 md:grid-cols-2 gap-6">{visibleCards.map(card => { const credit = card.type === 'credito'; const available = Math.max(0, card.limitTotal - card.limitUsed); return <div key={card.id} className="p-6 rounded-2xl bg-[#0F172A] border border-white/5 space-y-4"><div><span className="text-[10px] uppercase font-bold text-cyan-300">{credit ? 'Crédito' : 'Débito'}</span><h3 className="font-bold text-base text-white mt-1">{card.name}</h3><p className="text-xs text-slate-400">{card.institution} · {card.brand || 'Bandeira não informada'} · final {card.lastFourDigits || '—'}</p></div>{credit ? <div className="space-y-2 text-xs"><div className="flex justify-between"><span>Fatura atual</span><strong>{money(card.currentInvoice)}</strong></div><div className="flex justify-between text-slate-400"><span>Limite disponível</span><strong>{money(available)}</strong></div></div> : <p className="text-xs text-slate-400">Saldo da conta vinculada: consulte Contas PJ.</p>}{credit && <button onClick={() => onPayInvoice?.(card.id, card.currentInvoice)} className="w-full py-2.5 bg-cyan-600 text-white font-bold text-xs rounded-xl">Pagar fatura</button>}</div>; })}</div>}
  </div>;
}
