import { Transaction, TransactionAnalytics } from '../types';
import { MetricCard } from './aura/AuraCards';
import { Plus, ArrowRightLeft, BarChart3 } from 'lucide-react';

export function PjCashflow({ transactions = [], analytics, isPrivacyMode = false, onAddTransaction, onOpenTransferModal }: { transactions?: Transaction[]; analytics?: TransactionAnalytics; isPrivacyMode?: boolean; onAddTransaction?: () => void; onOpenTransferModal?: () => void }) {
  const rows = transactions.filter(row => row.context === 'PJ');
  const income = Number(analytics?.total_receipts_cents || 0) / 100 || rows.filter(row => row.type === 'income').reduce((sum, row) => sum + row.amount, 0);
  const expenses = Number(analytics?.total_expenses_cents || 0) / 100 || rows.filter(row => row.type === 'expense').reduce((sum, row) => sum + row.amount, 0);
  const balance = Number(analytics?.balance_cents || 0) / 100;
  const hasData = Boolean(analytics && analytics.transaction_count > 0) || rows.length > 0;
  return <div className="space-y-8 animate-in fade-in duration-200 text-slate-100"><div className="flex items-center justify-between border-b border-white/10 pb-4"><div><h1 className="text-2xl font-black text-white">Caixa Operacional Empresarial</h1><p className="text-xs text-slate-400 mt-1">Fluxo calculado com agregados e página real do Supabase.</p></div><div className="flex gap-2"><button onClick={onOpenTransferModal} className="flex items-center gap-2 px-3 py-2 bg-slate-900 rounded-xl text-xs font-bold"><ArrowRightLeft className="w-4 h-4" />Transferir</button><button onClick={onAddTransaction} className="flex items-center gap-2 px-3 py-2 bg-cyan-600 rounded-xl text-xs font-bold"><Plus className="w-4 h-4" />Nova movimentação</button></div></div>{!hasData ? <div className="p-16 text-center bg-[#0F172A] rounded-2xl border border-dashed border-white/10 text-slate-400"><BarChart3 className="w-10 h-10 mx-auto mb-3 text-slate-600" />Nenhum dado disponível</div> : <><div className="grid grid-cols-2 md:grid-cols-4 gap-4"><MetricCard title="Caixa atual" value={balance} isPrivacyMode={isPrivacyMode} subtitle="Agregado real" /><MetricCard title="Entradas" value={income} isPrivacyMode={isPrivacyMode} subtitle="Período filtrado" /><MetricCard title="Saídas" value={expenses} isPrivacyMode={isPrivacyMode} subtitle="Período filtrado" /><MetricCard title="Saldo do período" value={income - expenses} isPrivacyMode={isPrivacyMode} subtitle="Resultado calculado" /></div><div className="p-6 bg-[#0F172A] rounded-2xl border border-white/5 text-sm text-slate-300">Projeções futuras dependem de recebíveis e pagáveis reais; nenhum valor estimado é exibido sem fonte no Supabase.</div></>}</div>;
}
