import { CostCenter } from '../types';
import { MetricCard } from './aura/AuraCards';
import { Plus, PieChart } from 'lucide-react';

export function PjCostCentersView({ costCenters = [], isPrivacyMode = false }: { costCenters?: CostCenter[]; isPrivacyMode?: boolean }) {
  const budget = costCenters.reduce((sum, row) => sum + row.budgetAllocated, 0);
  if (costCenters.length === 0) return <div className="space-y-8 animate-in fade-in duration-200 text-slate-100"><div className="flex items-center justify-between border-b border-white/10 pb-4"><div><h1 className="text-2xl font-black text-white">Centros de Custo</h1><p className="text-xs text-slate-400 mt-1">Registros da organização ativa.</p></div><button onClick={() => alert('O cadastro de centros de custo ainda não possui uma fonte Supabase ativa.')} className="flex items-center gap-2 px-4 py-2.5 bg-cyan-600 text-white rounded-xl text-xs font-bold"><Plus className="w-4 h-4" />Novo centro</button></div><div className="p-16 text-center bg-[#0F172A] rounded-2xl border border-dashed border-white/10"><PieChart className="w-10 h-10 text-slate-600 mx-auto mb-3" /><p className="text-slate-400">Nenhum dado disponível</p></div></div>;
  return <div className="space-y-8 animate-in fade-in duration-200 text-slate-100"><div className="flex items-center justify-between border-b border-white/10 pb-4"><div><h1 className="text-2xl font-black text-white">Centros de Custo</h1><p className="text-xs text-slate-400 mt-1">Orçamentos cadastrados no Supabase.</p></div><button className="flex items-center gap-2 px-4 py-2.5 bg-cyan-600 text-white rounded-xl text-xs font-bold"><Plus className="w-4 h-4" />Novo centro</button></div><div className="grid grid-cols-2 md:grid-cols-2 gap-4"><MetricCard title="Centros ativos" value={costCenters.length} prefix="" subtitle="Registros reais" /><MetricCard title="Orçamento" value={budget} isPrivacyMode={isPrivacyMode} subtitle="Valor cadastrado" /></div>{costCenters.length === 0 ? <div className="p-16 text-center bg-[#0F172A] rounded-2xl border border-dashed border-white/10"><PieChart className="w-10 h-10 text-slate-600 mx-auto mb-3" /><p className="text-slate-400">Nenhum dado disponível</p></div> : <div className="grid grid-cols-1 md:grid-cols-2 gap-6">{costCenters.map(row => <div key={row.id} className="p-6 rounded-2xl bg-[#0F172A] border border-white/5 space-y-3"><h3 className="font-bold text-white">{row.name}</h3><div className="flex justify-between text-xs text-slate-500"><span>Orçamento</span><span>{row.budgetAllocated.toLocaleString('pt-BR', { style: 'currency', currency: 'BRL' })}</span></div><p className="text-xs text-slate-500">Gasto por centro: agregado server-side pendente de consulta.</p></div>)}</div>}</div>;
}
