import { useState, type ReactNode } from 'react';
import { Project, Customer, Supplier, CostCenter } from '../types';
import { MetricCard } from './aura/AuraCards';
import { Plus, Users, Truck } from 'lucide-react';

interface Props { projects?: Project[]; customers?: Customer[]; suppliers?: Supplier[]; costCenters?: CostCenter[]; isPrivacyMode?: boolean; onAddProject?: () => void; onAddCustomer?: () => void; onAddSupplier?: () => void; }
const money = (v: number) => v.toLocaleString('pt-BR', { style: 'currency', currency: 'BRL' });

export function PjManagement({ customers = [], suppliers = [], isPrivacyMode = false, onAddCustomer, onAddSupplier }: Props) {
  const [tab, setTab] = useState<'customers' | 'suppliers'>('customers');
  const [selected, setSelected] = useState<Customer | null>(null);
  const billed = customers.reduce((sum, row) => sum + row.totalBilled, 0);
  const pending = customers.reduce((sum, row) => sum + row.totalPending, 0);
  const spent = suppliers.reduce((sum, row) => sum + row.totalSpent, 0);
  if ((tab === 'customers' && customers.length === 0) || (tab === 'suppliers' && suppliers.length === 0)) {
    const showingCustomers = tab === 'customers';
    const addEntity = showingCustomers ? onAddCustomer : onAddSupplier;
    return <div className="space-y-8 animate-in fade-in duration-200 text-slate-100"><div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 border-b border-white/10 pb-4"><div><h1 className="text-2xl font-black text-white">Clientes &amp; Fornecedores</h1><p className="text-xs text-slate-400 mt-1">Cadastros da organização ativa.</p></div><div className="flex gap-1 p-1 bg-slate-900 rounded-xl border border-white/10"><button onClick={() => setTab('customers')} className={`px-4 py-2 rounded-lg text-xs font-bold ${showingCustomers ? 'bg-cyan-600 text-white' : 'text-slate-400'}`}>Clientes</button><button onClick={() => setTab('suppliers')} className={`px-4 py-2 rounded-lg text-xs font-bold ${!showingCustomers ? 'bg-cyan-600 text-white' : 'text-slate-400'}`}>Fornecedores</button></div></div><div className="p-16 text-center bg-[#0F172A] rounded-2xl border border-dashed border-white/10"><Users className="w-10 h-10 text-slate-600 mx-auto mb-3" /><p className="text-slate-400">Nenhum dado disponível</p><button onClick={() => addEntity ? addEntity() : alert('O cadastro ainda não possui uma fonte Supabase ativa.')} className="mt-4 px-4 py-2 bg-cyan-600 text-white rounded-xl text-xs font-bold">{showingCustomers ? 'Adicionar cliente' : 'Adicionar fornecedor'}</button></div></div>;
  }
  return <div className="space-y-8 animate-in fade-in duration-200 text-slate-100">
    <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 border-b border-white/10 pb-4"><div><h1 className="text-2xl font-black text-white">Clientes &amp; Fornecedores</h1><p className="text-xs text-slate-400 mt-1">Cadastros reais da organização ativa.</p></div><div className="flex gap-1 p-1 bg-slate-900 rounded-xl border border-white/10"><button onClick={() => setTab('customers')} className={`px-4 py-2 rounded-lg text-xs font-bold ${tab === 'customers' ? 'bg-cyan-600 text-white' : 'text-slate-400'}`}>Clientes ({customers.length})</button><button onClick={() => setTab('suppliers')} className={`px-4 py-2 rounded-lg text-xs font-bold ${tab === 'suppliers' ? 'bg-cyan-600 text-white' : 'text-slate-400'}`}>Fornecedores ({suppliers.length})</button></div></div>
    {tab === 'customers' ? <section className="space-y-6"><div className="grid grid-cols-2 md:grid-cols-3 gap-4"><MetricCard title="Clientes" value={customers.length} prefix="" subtitle="Registros reais" /><MetricCard title="Faturamento" value={billed} isPrivacyMode={isPrivacyMode} subtitle="Valor informado" /><MetricCard title="Em Aberto" value={pending} isPrivacyMode={isPrivacyMode} subtitle="Saldo informado" /></div><DataTable empty={!customers.length} headers={['Cliente', 'Documento', 'Contato', 'Faturado', 'Em aberto', 'Perfil']}><>{customers.map(row => <tr key={row.id} className="border-b border-white/5"><td className="py-3 px-4 font-bold">{row.name}</td><td className="py-3 px-4 text-slate-400">{row.documentCnpjCpf || '—'}</td><td className="py-3 px-4 text-slate-400">{row.contactEmail || '—'}</td><td className="py-3 px-4 text-right">{money(row.totalBilled)}</td><td className="py-3 px-4 text-right">{money(row.totalPending)}</td><td className="py-3 px-4 text-center"><button onClick={() => setSelected(row)} className="px-2 py-1 bg-slate-800 rounded text-cyan-300 text-[11px]">Ver</button></td></tr>)}</></DataTable><button onClick={onAddCustomer} className="flex items-center gap-2 px-4 py-2 bg-cyan-600 rounded-xl text-xs font-bold"><Plus className="w-4 h-4" />Novo cliente</button></section> : <section className="space-y-6"><div className="grid grid-cols-2 md:grid-cols-2 gap-4"><MetricCard title="Fornecedores" value={suppliers.length} prefix="" subtitle="Registros reais" /><MetricCard title="Gasto informado" value={spent} isPrivacyMode={isPrivacyMode} subtitle="Dados do Supabase" /></div><DataTable empty={!suppliers.length} headers={['Fornecedor', 'Categoria', 'CNPJ', 'E-mail', 'Total gasto']}><>{suppliers.map(row => <tr key={row.id} className="border-b border-white/5"><td className="py-3 px-4 font-bold">{row.name}</td><td className="py-3 px-4 text-slate-400">{row.category || '—'}</td><td className="py-3 px-4 text-slate-400">{row.documentCnpj || '—'}</td><td className="py-3 px-4 text-slate-400">{row.contactEmail || '—'}</td><td className="py-3 px-4 text-right">{money(row.totalSpent)}</td></tr>)}</></DataTable><button onClick={onAddSupplier} className="flex items-center gap-2 px-4 py-2 bg-cyan-600 rounded-xl text-xs font-bold"><Plus className="w-4 h-4" />Novo fornecedor</button></section>}
    {selected && <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-950/80"><div className="bg-[#0F172A] border border-white/10 rounded-2xl p-6 max-w-lg w-full space-y-4"><div className="flex justify-between"><h2 className="font-bold text-white">{selected.name}</h2><button onClick={() => setSelected(null)} className="text-slate-400">Fechar</button></div><div className="grid grid-cols-2 gap-3 text-xs"><div>Faturado<strong className="block text-white">{money(selected.totalBilled)}</strong></div><div>Recebido<strong className="block text-emerald-400">{money(selected.totalReceived)}</strong></div><div className="col-span-2">Pendente<strong className="block text-amber-400">{money(selected.totalPending)}</strong></div></div></div></div>}
  </div>;
}

function DataTable({ headers, empty, children }: { headers: string[]; empty: boolean; children: ReactNode }) { return <div className="bg-[#0F172A] rounded-2xl border border-white/5 overflow-hidden"><div className="p-4 border-b border-white/5 flex justify-end"><span className="text-xs text-slate-500">Fonte: Supabase</span></div>{empty ? <div className="py-16 text-center text-slate-400">Nenhum dado disponível</div> : <div className="overflow-x-auto"><table className="w-full text-left text-xs"><thead><tr className="bg-slate-900 text-slate-400 uppercase text-[10px]">{headers.map(header => <th key={header} className="py-3 px-4">{header}</th>)}</tr></thead><tbody>{children}</tbody></table></div>}</div>; }
