import { useState } from 'react';
import { Project, Customer } from '../types';
import { MetricCard } from './aura/AuraCards';
import { Plus, Briefcase } from 'lucide-react';

export function PjProjectsView({ projects = [], customers = [], isPrivacyMode = false, onAddProject }: { projects?: Project[]; customers?: Customer[]; isPrivacyMode?: boolean; onAddProject?: () => void }) {
  const [selected, setSelected] = useState<Project | null>(null);
  const contracted = projects.reduce((sum, row) => sum + (row.revenueContracted ?? row.revenue), 0);
  const received = projects.reduce((sum, row) => sum + (row.revenueReceived ?? 0), 0);
  const costs = projects.reduce((sum, row) => sum + (row.directCosts ?? row.cost), 0);
  if (projects.length === 0) return <div className="space-y-8 animate-in fade-in duration-200 text-slate-100"><div className="flex items-center justify-between border-b border-white/10 pb-4"><div><h1 className="text-2xl font-black text-white">Projetos &amp; Contratos</h1><p className="text-xs text-slate-400 mt-1">Registros da organização ativa.</p></div><button onClick={onAddProject} className="flex items-center gap-2 px-4 py-2 bg-cyan-600 rounded-xl text-xs font-bold"><Plus className="w-4 h-4" />Novo projeto</button></div><div className="p-16 text-center bg-[#0F172A] rounded-2xl border border-dashed border-white/10 text-slate-400"><Briefcase className="w-10 h-10 mx-auto mb-3 text-slate-600" />Nenhum dado disponível</div></div>;
  return <div className="space-y-8 animate-in fade-in duration-200 text-slate-100"><div className="flex items-center justify-between border-b border-white/10 pb-4"><div><h1 className="text-2xl font-black text-white">Projetos &amp; Contratos</h1><p className="text-xs text-slate-400 mt-1">Projetos reais da organização ativa.</p></div><button onClick={onAddProject} className="flex items-center gap-2 px-4 py-2 bg-cyan-600 rounded-xl text-xs font-bold"><Plus className="w-4 h-4" />Novo projeto</button></div><div className="grid grid-cols-2 md:grid-cols-4 gap-4"><MetricCard title="Projetos" value={projects.length} prefix="" subtitle="Registros reais" /><MetricCard title="Contratado" value={contracted} isPrivacyMode={isPrivacyMode} subtitle="Valor cadastrado" /><MetricCard title="Recebido" value={received} isPrivacyMode={isPrivacyMode} subtitle="Valor cadastrado" /><MetricCard title="Custos diretos" value={costs} isPrivacyMode={isPrivacyMode} subtitle="Valor cadastrado" /></div>{projects.length === 0 ? <div className="p-16 text-center bg-[#0F172A] rounded-2xl border border-dashed border-white/10 text-slate-400"><Briefcase className="w-10 h-10 mx-auto mb-3 text-slate-600" />Nenhum dado disponível</div> : <div className="bg-[#0F172A] rounded-2xl border border-white/5 overflow-hidden"><table className="w-full text-left text-xs"><thead><tr className="bg-slate-900 text-slate-400 uppercase text-[10px]"><th className="py-3 px-4">Projeto</th><th className="py-3 px-4">Cliente</th><th className="py-3 px-4 text-right">Contratado</th><th className="py-3 px-4 text-right">Recebido</th><th className="py-3 px-4">Status</th></tr></thead><tbody>{projects.map(row => <tr key={row.id} onClick={() => setSelected(row)} className="border-b border-white/5 cursor-pointer"><td className="py-3 px-4 font-bold">{row.name}</td><td className="py-3 px-4 text-slate-400">{row.client}</td><td className="py-3 px-4 text-right">{(row.revenueContracted ?? row.revenue).toLocaleString('pt-BR', { style: 'currency', currency: 'BRL' })}</td><td className="py-3 px-4 text-right">{(row.revenueReceived ?? 0).toLocaleString('pt-BR', { style: 'currency', currency: 'BRL' })}</td><td className="py-3 px-4">{row.status}</td></tr>)}</tbody></table></div>}{selected && <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-950/80"><div className="p-6 bg-[#0F172A] rounded-2xl border border-white/10 w-full max-w-md"><h2 className="font-bold text-white">{selected.name}</h2><p className="text-xs text-slate-400 mt-2">Cliente: {selected.client || 'Não informado'}</p><button onClick={() => setSelected(null)} className="mt-4 px-3 py-2 bg-slate-800 rounded-lg text-xs">Fechar</button></div></div>}</div>;
}
