import { Transaction, Account, Customer, Supplier, Project, CostCenter, Defaulter, CreditCard, TransactionAnalytics, TransactionQueryFilters } from '../types';
import { MetricCard } from './aura/AuraCards';
import { Download, FileText } from 'lucide-react';

interface Props { transactions?: Transaction[]; accounts?: Account[]; customers?: Customer[]; suppliers?: Supplier[]; projects?: Project[]; costCenters?: CostCenter[]; defaulters?: Defaulter[]; creditCards?: CreditCard[]; isPrivacyMode?: boolean; analytics?: TransactionAnalytics; onExportCsv?: (filters?: Pick<TransactionQueryFilters, 'startDate' | 'endDateExclusive'>) => Promise<string>; onNavigateTab?: (tab: string) => void; }
const money = (v: number) => v.toLocaleString('pt-BR', { style: 'currency', currency: 'BRL' });

export function PjReports({ transactions = [], accounts = [], customers = [], suppliers = [], projects = [], costCenters = [], defaulters = [], creditCards = [], isPrivacyMode = false, analytics, onExportCsv }: Props) {
  const hasData = Boolean(analytics && analytics.transaction_count > 0) || transactions.length > 0 || accounts.some(row => row.context === 'PJ') || customers.length > 0 || suppliers.length > 0 || projects.length > 0 || defaulters.length > 0 || creditCards.some(row => row.context === 'PJ');
  const revenue = Number(analytics?.total_receipts_cents || 0) / 100 || transactions.filter(row => row.context === 'PJ' && row.type === 'income').reduce((sum, row) => sum + row.amount, 0);
  const expenses = Number(analytics?.total_expenses_cents || 0) / 100 || transactions.filter(row => row.context === 'PJ' && row.type === 'expense').reduce((sum, row) => sum + row.amount, 0);
  const balance = Number(analytics?.balance_cents || 0) / 100;
  const categoryRows = (analytics?.by_category || []).filter(row => row.expenses_cents > 0);
  const delinquent = defaulters.reduce((sum, row) => sum + row.amount, 0);
  const exportReport = async () => { const csv = await onExportCsv?.(); if (!csv) return; const blob = new Blob([csv], { type: 'text/csv' }); const url = URL.createObjectURL(blob); const anchor = document.createElement('a'); anchor.href = url; anchor.download = 'aurafin-relatorio-pj.csv'; anchor.click(); URL.revokeObjectURL(url); };
  return <div className="space-y-8 animate-in fade-in duration-200 text-slate-100"><div className="flex items-center justify-between border-b border-white/10 pb-4"><div><h1 className="text-2xl font-black text-white">Relatórios PJ</h1><p className="text-xs text-slate-400 mt-1">Indicadores e listas calculados com dados da organização ativa.</p></div><button onClick={() => void exportReport()} className="flex items-center gap-2 px-4 py-2 bg-cyan-600 text-white rounded-xl text-xs font-bold"><Download className="w-4 h-4" />Exportar CSV</button></div>{!hasData ? <div className="p-16 text-center bg-[#0F172A] rounded-2xl border border-dashed border-white/10 text-slate-400"><FileText className="w-10 h-10 mx-auto mb-3 text-slate-600" />Nenhum dado disponível</div> : <><div className="grid grid-cols-2 md:grid-cols-4 gap-4"><MetricCard title="Receitas" value={revenue} isPrivacyMode={isPrivacyMode} subtitle="Agregado real" /><MetricCard title="Despesas" value={expenses} isPrivacyMode={isPrivacyMode} subtitle="Agregado real" /><MetricCard title="Saldo" value={balance} isPrivacyMode={isPrivacyMode} subtitle="Agregado real" /><MetricCard title="Inadimplência" value={delinquent} isPrivacyMode={isPrivacyMode} subtitle="View v_defaulters" /></div><div className="grid grid-cols-1 lg:grid-cols-2 gap-6"><section className="p-6 bg-[#0F172A] rounded-2xl border border-white/5"><h2 className="font-bold text-white mb-4">Despesas por categoria</h2>{categoryRows.length === 0 ? <p className="text-sm text-slate-400">Nenhum dado disponível</p> : <div className="space-y-3">{categoryRows.map(row => <div key={row.category} className="flex justify-between text-sm"><span className="text-slate-300">{row.category}</span><strong>{money(row.expenses_cents / 100)}</strong></div>)}</div>}</section><section className="p-6 bg-[#0F172A] rounded-2xl border border-white/5"><h2 className="font-bold text-white mb-4">Projetos</h2>{projects.length === 0 ? <p className="text-sm text-slate-400">Nenhum dado disponível</p> : <div className="space-y-3">{projects.map(row => <div key={row.id} className="flex justify-between text-sm"><span className="text-slate-300">{row.name}</span><strong>{money(row.revenueContracted ?? row.revenue)}</strong></div>)}</div>}</section></div></>}</div>;
}
